import type { LegalAct } from "./types";

/**
 * Reference data for study purposes. BNS/BNSS/BSA section numbers reflect
 * widely reported renumbering from the 2023 codes — always cross-check
 * against the official Bare Act before relying on them in exams or filings.
 */
export const legalActs: LegalAct[] = [
  {
    id: "constitution",
    name: "The Constitution of India",
    shortName: "Constitution",
    year: 1950,
    category: "Constitution",
    status: "current",
    inForceNote: "In force since 26 January 1950",
    summary:
      "The supreme law of India, establishing fundamental rights, directive principles, and the structure of government.",
    provisions: [
      { label: "Article 14", description: "Equality before law and equal protection of laws" },
      { label: "Article 19", description: "Protection of six freedoms, including speech and expression" },
      { label: "Article 21", description: "Protection of life and personal liberty" },
      { label: "Article 32", description: "Right to constitutional remedies before the Supreme Court" },
      { label: "Article 368", description: "Power of Parliament to amend the Constitution" },
    ],
    amendments: [
      "42nd Amendment (1976) — inserted 'socialist' and 'secular' into the Preamble; added Fundamental Duties (Article 51A)",
      "44th Amendment (1978) — restored safeguards diluted during the Emergency",
      "73rd & 74th Amendments (1992) — constitutional status for Panchayati Raj and Municipalities",
    ],
  },
  {
    id: "bns",
    name: "Bharatiya Nyaya Sanhita, 2023",
    shortName: "BNS",
    year: 2023,
    category: "Criminal Law",
    status: "current",
    supersedes: "Indian Penal Code, 1860",
    inForceNote: "In force since 1 July 2024",
    summary:
      "The current substantive criminal code of India, replacing the Indian Penal Code, 1860, with revised offence definitions and renumbered sections.",
    provisions: [
      { label: "Section 103", description: "Punishment for murder (corresponds to Section 302, IPC 1860)" },
      { label: "Section 105", description: "Culpable homicide not amounting to murder (corresponds to Section 304, IPC 1860)" },
      { label: "Section 63", description: "Definition of rape (corresponds to Section 375, IPC 1860)" },
      { label: "Section 152", description: "Acts endangering sovereignty, unity and integrity of India (replaces sedition under Section 124A, IPC 1860)" },
    ],
    amendments: [],
  },
  {
    id: "ipc",
    name: "The Indian Penal Code, 1860",
    shortName: "IPC",
    year: 1860,
    category: "Criminal Law",
    status: "historical",
    supersededBy: "Bharatiya Nyaya Sanhita, 2023",
    inForceNote: "Repealed and replaced by the BNS with effect from 1 July 2024",
    summary:
      "India's original substantive criminal code, in force for over 160 years before being replaced by the BNS. Still relevant for offences committed before 1 July 2024 and for understanding case law built on it.",
    provisions: [
      { label: "Section 299", description: "Definition of culpable homicide" },
      { label: "Section 300", description: "Definition of murder and its exceptions" },
      { label: "Section 302", description: "Punishment for murder" },
      { label: "Section 304", description: "Punishment for culpable homicide not amounting to murder" },
      { label: "Section 375 / 376", description: "Rape — definition and punishment" },
    ],
    amendments: ["Criminal Law (Amendment) Act, 2013 — expanded the definition of rape and sexual offences after the Nirbhaya case"],
  },
  {
    id: "bnss",
    name: "Bharatiya Nagarik Suraksha Sanhita, 2023",
    shortName: "BNSS",
    year: 2023,
    category: "Procedural Law",
    status: "current",
    supersedes: "Code of Criminal Procedure, 1973",
    inForceNote: "In force since 1 July 2024",
    summary: "The current law of criminal procedure, replacing the CrPC, 1973, with provisions for timelines, forensics, and electronic processes.",
    provisions: [
      { label: "Section 173", description: "Registration of an FIR, including electronic filing (corresponds to Section 154, CrPC 1973)" },
    ],
    amendments: [],
  },
  {
    id: "crpc",
    name: "The Code of Criminal Procedure, 1973",
    shortName: "CrPC",
    year: 1973,
    category: "Procedural Law",
    status: "historical",
    supersededBy: "Bharatiya Nagarik Suraksha Sanhita, 2023",
    inForceNote: "Repealed and replaced by the BNSS with effect from 1 July 2024",
    summary: "Governed criminal procedure in India for five decades, including investigation, trial, bail, and appeal processes.",
    provisions: [
      { label: "Section 154", description: "Information in cognizable cases (FIR)" },
      { label: "Section 161", description: "Examination of witnesses by police" },
      { label: "Section 41", description: "When police may arrest without a warrant" },
    ],
    amendments: [],
  },
  {
    id: "bsa",
    name: "Bharatiya Sakshya Adhiniyam, 2023",
    shortName: "BSA",
    year: 2023,
    category: "Procedural Law",
    status: "current",
    supersedes: "Indian Evidence Act, 1872",
    inForceNote: "In force since 1 July 2024",
    summary: "The current law of evidence, replacing the Indian Evidence Act, 1872, with expanded provisions for electronic and digital evidence.",
    provisions: [
      { label: "Section 63", description: "Admissibility of electronic records (corresponds to Section 65B, Evidence Act 1872)" },
    ],
    amendments: [],
  },
  {
    id: "evidence-act",
    name: "The Indian Evidence Act, 1872",
    shortName: "Evidence Act",
    year: 1872,
    category: "Procedural Law",
    status: "historical",
    supersededBy: "Bharatiya Sakshya Adhiniyam, 2023",
    inForceNote: "Repealed and replaced by the BSA with effect from 1 July 2024",
    summary: "Governed the admissibility and relevance of evidence in Indian courts for over 150 years.",
    provisions: [
      { label: "Section 65B", description: "Admissibility of electronic records" },
      { label: "Section 3", description: "Definitions — 'evidence', 'fact', 'proved'" },
    ],
    amendments: [],
  },
  {
    id: "contract-act",
    name: "The Indian Contract Act, 1872",
    shortName: "Contract Act",
    year: 1872,
    category: "Civil Law",
    status: "current",
    inForceNote: "In force since 1 September 1872",
    summary: "Governs the formation, performance, and enforcement of contracts in India.",
    provisions: [
      { label: "Section 10", description: "What agreements are contracts" },
      { label: "Section 11", description: "Who is competent to contract" },
      { label: "Section 23", description: "Lawful consideration and object" },
      { label: "Section 73", description: "Compensation for loss caused by breach of contract" },
    ],
    amendments: [],
  },
  {
    id: "top-act",
    name: "The Transfer of Property Act, 1882",
    shortName: "TP Act",
    year: 1882,
    category: "Civil Law",
    status: "current",
    inForceNote: "In force since 1 July 1882",
    summary: "Regulates the transfer of immovable property between living persons.",
    provisions: [
      { label: "Section 5", description: "Definition of 'transfer of property'" },
      { label: "Section 54", description: "Definition of 'sale' of immovable property" },
    ],
    amendments: [],
  },
  {
    id: "cpc",
    name: "The Code of Civil Procedure, 1908",
    shortName: "CPC",
    year: 1908,
    category: "Procedural Law",
    status: "current",
    inForceNote: "In force since 1 January 1909",
    summary: "Governs the procedure for civil litigation in Indian courts, from filing a suit to execution of a decree.",
    provisions: [
      { label: "Section 9", description: "Courts to try all civil suits unless barred" },
      { label: "Order VII Rule 11", description: "Rejection of plaint" },
    ],
    amendments: [],
  },
  {
    id: "companies-act",
    name: "The Companies Act, 2013",
    shortName: "Companies Act",
    year: 2013,
    category: "Commercial Law",
    status: "current",
    inForceNote: "Progressively in force since 2013–2014",
    summary: "Governs the incorporation, governance, and regulation of companies in India.",
    provisions: [
      { label: "Section 2(20)", description: "Definition of 'company'" },
      { label: "Section 149", description: "Composition of the board of directors" },
    ],
    amendments: [],
  },
  {
    id: "it-act",
    name: "The Information Technology Act, 2000",
    shortName: "IT Act",
    year: 2000,
    category: "Other Central Acts",
    status: "current",
    inForceNote: "In force since 17 October 2000",
    summary: "India's principal law on electronic governance, cybercrime, and digital transactions.",
    provisions: [
      { label: "Section 66A", description: "Punishment for offensive messages — struck down as unconstitutional in Shreya Singhal v. Union of India (2015)" },
      { label: "Section 43", description: "Penalty for damage to computer systems" },
    ],
    amendments: ["IT (Amendment) Act, 2008 — expanded cybercrime provisions"],
  },
];

export function getActById(id: string) {
  return legalActs.find((a) => a.id === id);
}
