import {
  Landmark,
  Gavel,
  FileSignature,
  ShieldAlert,
  Home,
  Users,
  Building2,
  Scale,
  FileStack,
  ClipboardList,
  FileSearch,
  BookOpenText,
  Globe2,
  Leaf,
  HardHat,
  Lightbulb,
  History,
  Languages,
  Vote,
  TrendingUp,
  HeartHandshake,
  PenLine,
  Presentation,
  Percent,
  Handshake,
  Wallet,
  ShieldCheck,
  Wifi,
  Fingerprint,
  LifeBuoy,
  BadgeCheck,
  FlaskConical,
  Ship,
  Newspaper,
  ShoppingCart,
  Brain,
  Puzzle,
  Calculator,
  MapPin,
  BookOpenCheck,
  ListChecks,
  UserRound,
  Banknote,
  Scroll,
  Briefcase,
  Megaphone,
  Target,
  LineChart,
  type LucideIcon,
} from "lucide-react";

export const subjectIconMap: Record<string, LucideIcon> = {
  Landmark,
  Gavel,
  FileSignature,
  ShieldAlert,
  Home,
  Users,
  Building2,
  Scale,
  FileStack,
  ClipboardList,
  FileSearch,
  BookOpenText,
  Globe2,
  Leaf,
  HardHat,
  Lightbulb,
  History,
  Languages,
  Vote,
  TrendingUp,
  HeartHandshake,
  PenLine,
  Presentation,
  Percent,
  Handshake,
  Wallet,
  ShieldCheck,
  Wifi,
  Fingerprint,
  LifeBuoy,
  BadgeCheck,
  FlaskConical,
  Ship,
  Newspaper,
  ShoppingCart,
  Brain,
  Puzzle,
  Calculator,
  MapPin,
  BookOpenCheck,
  ListChecks,
  UserRound,
  Banknote,
  Scroll,
  Briefcase,
  Megaphone,
  Target,
  LineChart,
};

export function getSubjectIcon(name: string): LucideIcon {
  return subjectIconMap[name] ?? Scale;
}

/**
 * Renders a subject icon from a dynamic name lookup. Plain (lowercase) helper
 * function rather than a component so the icon-by-name pattern doesn't trip
 * react-hooks/static-components, which flags JSX tags resolved from a
 * variable computed during a component's render.
 */
export function renderSubjectIcon(name: string, className?: string) {
  const Icon = subjectIconMap[name] ?? Scale;
  return <Icon className={className} aria-hidden="true" />;
}
