import type { Subject } from "./types";

export const subjects: Subject[] = [
  {
    slug: "constitutional-law",
    name: "Constitutional Law",
    shortName: "Constitution",
    description: "Fundamental rights, directive principles, and the structure of the Indian state.",
    icon: "Landmark",
    progress: 68,
    topicsCompleted: 17,
    topicsTotal: 25,
    questionsAsked: 142,
    lastStudied: "2026-08-09",
  },
  {
    slug: "criminal-law",
    name: "Criminal Law",
    shortName: "Criminal",
    description: "BNS 2023, historical IPC framework, and the elements of criminal liability.",
    icon: "Gavel",
    progress: 54,
    topicsCompleted: 13,
    topicsTotal: 24,
    questionsAsked: 118,
    lastStudied: "2026-08-08",
  },
  {
    slug: "contract-law",
    name: "Contract Law",
    shortName: "Contracts",
    description: "Offer, acceptance, consideration, and the law of agreements.",
    icon: "FileSignature",
    progress: 41,
    topicsCompleted: 9,
    topicsTotal: 22,
    questionsAsked: 76,
    lastStudied: "2026-08-06",
  },
  {
    slug: "tort-law",
    name: "Tort Law",
    shortName: "Torts",
    description: "Civil wrongs, negligence, strict and absolute liability.",
    icon: "ShieldAlert",
    progress: 33,
    topicsCompleted: 6,
    topicsTotal: 18,
    questionsAsked: 42,
    lastStudied: "2026-08-02",
  },
  {
    slug: "property-law",
    name: "Property Law",
    shortName: "Property",
    description: "Transfer of Property Act, ownership, and possession.",
    icon: "Home",
    progress: 22,
    topicsCompleted: 4,
    topicsTotal: 18,
    questionsAsked: 25,
    lastStudied: "2026-07-28",
  },
  {
    slug: "family-law",
    name: "Family Law",
    shortName: "Family",
    description: "Marriage, divorce, succession, and personal laws.",
    icon: "Users",
    progress: 15,
    topicsCompleted: 3,
    topicsTotal: 20,
    questionsAsked: 18,
    lastStudied: "2026-07-20",
  },
  {
    slug: "company-law",
    name: "Company Law",
    shortName: "Company",
    description: "Incorporation, corporate governance, and the Companies Act, 2013.",
    icon: "Building2",
    progress: 12,
    topicsCompleted: 2,
    topicsTotal: 16,
    questionsAsked: 11,
    lastStudied: "2026-07-14",
  },
  {
    slug: "administrative-law",
    name: "Administrative Law",
    shortName: "Admin Law",
    description: "Delegated legislation, natural justice, and judicial review of executive action.",
    icon: "Scale",
    progress: 28,
    topicsCompleted: 5,
    topicsTotal: 16,
    questionsAsked: 31,
    lastStudied: "2026-07-30",
  },
  {
    slug: "cpc",
    name: "Code of Civil Procedure",
    shortName: "CPC",
    description: "Civil litigation procedure under the CPC, 1908.",
    icon: "FileStack",
    progress: 9,
    topicsCompleted: 2,
    topicsTotal: 20,
    questionsAsked: 8,
    lastStudied: null,
  },
  {
    slug: "bnss",
    name: "BNSS",
    shortName: "BNSS",
    description: "Bharatiya Nagarik Suraksha Sanhita, 2023 — current criminal procedure law.",
    icon: "ClipboardList",
    progress: 19,
    topicsCompleted: 4,
    topicsTotal: 20,
    questionsAsked: 22,
    lastStudied: "2026-07-25",
  },
  {
    slug: "evidence-bsa",
    name: "Evidence Law",
    shortName: "BSA",
    description: "Bharatiya Sakshya Adhiniyam, 2023 and the historical Evidence Act, 1872.",
    icon: "FileSearch",
    progress: 24,
    topicsCompleted: 5,
    topicsTotal: 18,
    questionsAsked: 29,
    lastStudied: "2026-08-01",
  },
  {
    slug: "jurisprudence",
    name: "Jurisprudence",
    shortName: "Jurisprudence",
    description: "Legal theory, schools of thought, and the philosophy of law.",
    icon: "BookOpenText",
    progress: 31,
    topicsCompleted: 6,
    topicsTotal: 16,
    questionsAsked: 34,
    lastStudied: "2026-07-31",
  },
  {
    slug: "international-law",
    name: "International Law",
    shortName: "Intl. Law",
    description: "Treaties, state responsibility, and public international law.",
    icon: "Globe2",
    progress: 6,
    topicsCompleted: 1,
    topicsTotal: 14,
    questionsAsked: 4,
    lastStudied: null,
  },
  {
    slug: "environmental-law",
    name: "Environmental Law",
    shortName: "Environment",
    description: "Absolute liability, sustainable development, and environmental statutes.",
    icon: "Leaf",
    progress: 17,
    topicsCompleted: 3,
    topicsTotal: 14,
    questionsAsked: 15,
    lastStudied: "2026-07-18",
  },
  {
    slug: "labour-law",
    name: "Labour Law",
    shortName: "Labour",
    description: "Industrial relations, workplace rights, and welfare legislation.",
    icon: "HardHat",
    progress: 4,
    topicsCompleted: 1,
    topicsTotal: 15,
    questionsAsked: 3,
    lastStudied: null,
  },
  {
    slug: "intellectual-property",
    name: "Intellectual Property",
    shortName: "IP Law",
    description: "Patents, trademarks, copyright, and the law of ideas.",
    icon: "Lightbulb",
    progress: 8,
    topicsCompleted: 2,
    topicsTotal: 16,
    questionsAsked: 9,
    lastStudied: "2026-07-10",
  },
];

export function getSubjectBySlug(slug: string) {
  return subjects.find((s) => s.slug === slug);
}
