import type { Subject } from "./types";

/**
 * The full subject registry: the original 16 "rich" subjects (which carry curated
 * quiz questions, flashcards, and landmark cases in quiz.ts/flashcards.ts/cases.ts)
 * plus the complete law-school (Year 1-5), CLAT, and Judiciary curriculum.
 *
 * Curriculum entries that cover the same doctrinal ground as a rich subject set
 * `linkedSubjectSlug` to that rich subject's slug, so their subject page can surface
 * its real practice content instead of duplicating (or fabricating) new content.
 * `tracks` records which onboarding preparation choices include this subject, used
 * to personalize the dashboard, /subjects, and onboarding's subject picker.
 */
export const subjects: Subject[] = [
  // ---------------------------------------------------------------------------
  // Rich subjects — carry curated quiz questions, flashcards, and landmark cases.
  // ---------------------------------------------------------------------------
  {
    slug: "constitutional-law",
    name: "Constitutional Law",
    shortName: "Constitution",
    description: "Fundamental rights, directive principles, and the structure of the Indian state.",
    icon: "Landmark",
    tracks: ["1st Year Law", "2nd Year Law", "Judiciary"],
    relatedActIds: ["constitution"],
  },
  {
    slug: "criminal-law",
    name: "Criminal Law",
    shortName: "Criminal",
    description: "BNS 2023, historical IPC framework, and the elements of criminal liability.",
    icon: "Gavel",
    tracks: ["2nd Year Law", "Judiciary"],
    relatedActIds: ["bns", "ipc"],
  },
  {
    slug: "contract-law",
    name: "Contract Law",
    shortName: "Contracts",
    description: "Offer, acceptance, consideration, and the law of agreements.",
    icon: "FileSignature",
    tracks: ["1st Year Law", "2nd Year Law", "Judiciary"],
    relatedActIds: ["contract-act"],
  },
  {
    slug: "tort-law",
    name: "Tort Law",
    shortName: "Torts",
    description: "Civil wrongs, negligence, strict and absolute liability.",
    icon: "ShieldAlert",
    tracks: ["1st Year Law", "Judiciary"],
  },
  {
    slug: "property-law",
    name: "Property Law",
    shortName: "Property",
    description: "Transfer of Property Act, ownership, and possession.",
    icon: "Home",
    tracks: ["3rd Year Law", "Judiciary"],
    relatedActIds: ["top-act"],
  },
  {
    slug: "family-law",
    name: "Family Law",
    shortName: "Family",
    description: "Marriage, divorce, succession, and personal laws.",
    icon: "Users",
    tracks: ["2nd Year Law", "Judiciary"],
  },
  {
    slug: "company-law",
    name: "Company Law",
    shortName: "Company",
    description: "Incorporation, corporate governance, and the Companies Act, 2013.",
    icon: "Building2",
    tracks: ["3rd Year Law", "4th Year Law"],
    relatedActIds: ["companies-act"],
  },
  {
    slug: "administrative-law",
    name: "Administrative Law",
    shortName: "Admin Law",
    description: "Delegated legislation, natural justice, and judicial review of executive action.",
    icon: "Scale",
    tracks: ["2nd Year Law", "5th Year Law", "Judiciary"],
  },
  {
    slug: "cpc",
    name: "Code of Civil Procedure",
    shortName: "CPC",
    description: "Civil litigation procedure under the CPC, 1908.",
    icon: "FileStack",
    tracks: ["3rd Year Law", "Judiciary"],
    relatedActIds: ["cpc"],
  },
  {
    slug: "bnss",
    name: "BNSS",
    shortName: "BNSS",
    description: "Bharatiya Nagarik Suraksha Sanhita, 2023 — current criminal procedure law.",
    icon: "ClipboardList",
    tracks: ["3rd Year Law", "Judiciary"],
    relatedActIds: ["bnss", "crpc"],
  },
  {
    slug: "evidence-bsa",
    name: "Evidence Law",
    shortName: "BSA",
    description: "Bharatiya Sakshya Adhiniyam, 2023 and the historical Evidence Act, 1872.",
    icon: "FileSearch",
    tracks: ["2nd Year Law", "Judiciary"],
    relatedActIds: ["bsa", "evidence-act"],
  },
  {
    slug: "jurisprudence",
    name: "Jurisprudence",
    shortName: "Jurisprudence",
    description: "Legal theory, schools of thought, and the philosophy of law.",
    icon: "BookOpenText",
    tracks: ["3rd Year Law", "4th Year Law"],
  },
  {
    slug: "international-law",
    name: "International Law",
    shortName: "Intl. Law",
    description: "Treaties, state responsibility, and public international law.",
    icon: "Globe2",
    tracks: ["4th Year Law"],
  },
  {
    slug: "environmental-law",
    name: "Environmental Law",
    shortName: "Environment",
    description: "Absolute liability, sustainable development, and environmental statutes.",
    icon: "Leaf",
    tracks: ["3rd Year Law"],
  },
  {
    slug: "labour-law",
    name: "Labour Law",
    shortName: "Labour",
    description: "Industrial relations, workplace rights, and welfare legislation.",
    icon: "HardHat",
    tracks: ["3rd Year Law", "4th Year Law"],
  },
  {
    slug: "intellectual-property",
    name: "Intellectual Property",
    shortName: "IP Law",
    description: "Patents, trademarks, copyright, and the law of ideas.",
    icon: "Lightbulb",
    tracks: ["4th Year Law"],
  },

  // ---------------------------------------------------------------------------
  // Year 1 — Foundations
  // ---------------------------------------------------------------------------
  {
    slug: "legal-methods",
    name: "Legal Methods & Legal Reasoning",
    shortName: "Legal Methods",
    description: "Foundational skills in statutory interpretation, legal research, and structured legal reasoning.",
    icon: "Scale",
    tracks: ["1st Year Law"],
  },
  {
    slug: "constitutional-law-i",
    name: "Constitutional Law I",
    shortName: "Const. Law I",
    description: "Introduces the structure of the Indian Constitution, the Union and State organs, and citizenship.",
    icon: "Landmark",
    tracks: ["1st Year Law"],
    linkedSubjectSlug: "constitutional-law",
  },
  {
    slug: "contract-law-i",
    name: "Law of Contract I",
    shortName: "Contract I",
    description: "Formation of contracts — offer, acceptance, consideration, and capacity to contract.",
    icon: "FileSignature",
    tracks: ["1st Year Law"],
    linkedSubjectSlug: "contract-law",
  },
  {
    slug: "tort-law-i",
    name: "Law of Torts I",
    shortName: "Torts I",
    description: "General principles of tortious liability, negligence, and defences to a tort claim.",
    icon: "ShieldAlert",
    tracks: ["1st Year Law"],
    linkedSubjectSlug: "tort-law",
  },
  {
    slug: "legal-history",
    name: "Legal History & Legal Systems",
    shortName: "Legal History",
    description: "The evolution of Indian law from ancient and colonial sources to the modern legal system.",
    icon: "History",
    tracks: ["1st Year Law"],
  },
  {
    slug: "legal-language",
    name: "English & Legal Language",
    shortName: "Legal Language",
    description: "Legal vocabulary, drafting conventions, and precise written and spoken communication for law students.",
    icon: "Languages",
    tracks: ["1st Year Law"],
  },
  {
    slug: "political-science-i",
    name: "Political Science I",
    shortName: "Pol. Science",
    description: "Core concepts of the state, sovereignty, political theory, and comparative government relevant to law.",
    icon: "Vote",
    tracks: ["1st Year Law"],
  },
  {
    slug: "economics-for-law",
    name: "Economics for Law",
    shortName: "Economics",
    description: "Basic micro- and macroeconomic principles and their application to law and public policy.",
    icon: "TrendingUp",
    tracks: ["1st Year Law"],
  },

  // ---------------------------------------------------------------------------
  // Year 2 — Core Law
  // ---------------------------------------------------------------------------
  {
    slug: "constitutional-law-ii",
    name: "Constitutional Law II",
    shortName: "Const. Law II",
    description: "Fundamental Rights, Directive Principles, and constitutional remedies under the Indian Constitution.",
    icon: "Landmark",
    tracks: ["2nd Year Law"],
    linkedSubjectSlug: "constitutional-law",
  },
  {
    slug: "crimes-i",
    name: "Law of Crimes I (IPC / BNS — General Principles)",
    shortName: "Crimes I",
    description: "General principles of criminal liability — mens rea, actus reus, and stages of a crime — under the BNS and historical IPC.",
    icon: "Gavel",
    tracks: ["2nd Year Law"],
    linkedSubjectSlug: "criminal-law",
  },
  {
    slug: "crimes-ii",
    name: "Law of Crimes II (IPC / BNS — Specific Offences)",
    shortName: "Crimes II",
    description: "Specific offences against the person, property, and the state under the BNS and historical IPC.",
    icon: "Gavel",
    tracks: ["2nd Year Law"],
    linkedSubjectSlug: "criminal-law",
  },
  {
    slug: "family-law-i-hindu",
    name: "Family Law I — Hindu Law",
    shortName: "Family Law I",
    description: "Marriage, divorce, maintenance, and succession under codified Hindu personal law.",
    icon: "Users",
    tracks: ["2nd Year Law"],
    linkedSubjectSlug: "family-law",
  },
  {
    slug: "family-law-ii-muslim-christian",
    name: "Family Law II — Muslim Law & Christian Law",
    shortName: "Family Law II",
    description: "Marriage, dissolution, and succession under Muslim personal law and Christian personal law.",
    icon: "Users",
    tracks: ["2nd Year Law"],
    linkedSubjectSlug: "family-law",
  },
  {
    slug: "evidence-i",
    name: "Law of Evidence I (IEA / BSA)",
    shortName: "Evidence I",
    description: "Relevance, admissibility, and the burden of proof under the BSA and the historical Evidence Act.",
    icon: "FileSearch",
    tracks: ["2nd Year Law"],
    linkedSubjectSlug: "evidence-bsa",
  },
  {
    slug: "evidence-ii",
    name: "Law of Evidence II (IEA / BSA — Advanced)",
    shortName: "Evidence II",
    description: "Witnesses, documentary evidence, presumptions, and privileged communication under the BSA and historical Evidence Act.",
    icon: "FileSearch",
    tracks: ["2nd Year Law"],
    linkedSubjectSlug: "evidence-bsa",
  },
  {
    slug: "contract-law-ii",
    name: "Law of Contract II — Special Contracts",
    shortName: "Contract II",
    description: "Special contracts — indemnity, guarantee, bailment, pledge, agency, and sale of goods.",
    icon: "FileSignature",
    tracks: ["2nd Year Law"],
    linkedSubjectSlug: "contract-law",
  },
  {
    slug: "administrative-law-i",
    name: "Administrative Law I",
    shortName: "Admin Law I",
    description: "Delegated legislation, natural justice, and control over administrative action.",
    icon: "Scale",
    tracks: ["2nd Year Law"],
    linkedSubjectSlug: "administrative-law",
  },
  {
    slug: "sociology-for-lawyers",
    name: "Sociology for Lawyers",
    shortName: "Sociology",
    description: "The relationship between law and society, and the social context in which legal rules operate.",
    icon: "HeartHandshake",
    tracks: ["2nd Year Law"],
  },

  // ---------------------------------------------------------------------------
  // Year 3 — Procedure & Practice
  // ---------------------------------------------------------------------------
  {
    slug: "cpc-i",
    name: "Code of Civil Procedure I (CPC)",
    shortName: "CPC I",
    description: "Jurisdiction, res judicata, pleadings, and the framework of a civil suit under the CPC, 1908.",
    icon: "FileStack",
    tracks: ["3rd Year Law"],
    linkedSubjectSlug: "cpc",
  },
  {
    slug: "cpc-ii",
    name: "Code of Civil Procedure II (CPC)",
    shortName: "CPC II",
    description: "Execution of decrees, appeals, review, revision, and interim remedies under the CPC, 1908.",
    icon: "FileStack",
    tracks: ["3rd Year Law"],
    linkedSubjectSlug: "cpc",
  },
  {
    slug: "crpc-i",
    name: "Criminal Procedure I (CrPC / BNSS)",
    shortName: "CrPC I",
    description: "Arrest, investigation, and the machinery of criminal justice under the BNSS and historical CrPC.",
    icon: "ClipboardList",
    tracks: ["3rd Year Law"],
    linkedSubjectSlug: "bnss",
  },
  {
    slug: "crpc-ii",
    name: "Criminal Procedure II (CrPC / BNSS)",
    shortName: "CrPC II",
    description: "Trial procedure, bail, and appeals under the BNSS and historical CrPC.",
    icon: "ClipboardList",
    tracks: ["3rd Year Law"],
    linkedSubjectSlug: "bnss",
  },
  {
    slug: "top-i",
    name: "Transfer of Property Act I",
    shortName: "TOPA I",
    description: "General principles of transfer of property, and sale and mortgage under the Transfer of Property Act, 1882.",
    icon: "Home",
    tracks: ["3rd Year Law"],
    linkedSubjectSlug: "property-law",
  },
  {
    slug: "top-ii",
    name: "Transfer of Property Act II",
    shortName: "TOPA II",
    description: "Lease, gift, actionable claims, and other specific transfers under the Transfer of Property Act, 1882.",
    icon: "Home",
    tracks: ["3rd Year Law"],
    linkedSubjectSlug: "property-law",
  },
  {
    slug: "jurisprudence-i",
    name: "Jurisprudence I",
    shortName: "Jurisprudence I",
    description: "Schools of legal theory and foundational concepts such as law, rights, and justice.",
    icon: "BookOpenText",
    tracks: ["3rd Year Law"],
    linkedSubjectSlug: "jurisprudence",
  },
  {
    slug: "company-law-i",
    name: "Company Law I",
    shortName: "Company I",
    description: "Incorporation, memorandum and articles, and the corporate personality under the Companies Act, 2013.",
    icon: "Building2",
    tracks: ["3rd Year Law"],
    linkedSubjectSlug: "company-law",
  },
  {
    slug: "labour-law-i",
    name: "Labour & Industrial Law I",
    shortName: "Labour I",
    description: "Industrial relations, trade unions, and the resolution of industrial disputes.",
    icon: "HardHat",
    tracks: ["3rd Year Law"],
    linkedSubjectSlug: "labour-law",
  },
  {
    slug: "drafting-pleading-i",
    name: "Drafting, Pleading & Conveyancing I",
    shortName: "Drafting I",
    description: "Foundational skills in drafting pleadings, petitions, and basic conveyancing documents.",
    icon: "PenLine",
    tracks: ["3rd Year Law"],
  },
  {
    slug: "moot-court-i",
    name: "Moot Court & Trial Advocacy I",
    shortName: "Moot Court I",
    description: "Introductory courtroom advocacy skills through mooting, memorial drafting, and oral argument.",
    icon: "Presentation",
    tracks: ["3rd Year Law"],
  },

  // ---------------------------------------------------------------------------
  // Year 4 — Specialisations
  // ---------------------------------------------------------------------------
  {
    slug: "jurisprudence-ii",
    name: "Jurisprudence II",
    shortName: "Jurisprudence II",
    description: "Contemporary jurisprudential schools — realism, sociological, and critical legal theory.",
    icon: "BookOpenText",
    tracks: ["4th Year Law"],
    linkedSubjectSlug: "jurisprudence",
  },
  {
    slug: "company-law-ii",
    name: "Company Law II",
    shortName: "Company II",
    description: "Corporate governance, meetings, mergers, and winding up under the Companies Act, 2013.",
    icon: "Building2",
    tracks: ["4th Year Law"],
    linkedSubjectSlug: "company-law",
  },
  {
    slug: "labour-law-ii",
    name: "Labour & Industrial Law II",
    shortName: "Labour II",
    description: "Wages, social security, and welfare legislation for workers.",
    icon: "HardHat",
    tracks: ["4th Year Law"],
    linkedSubjectSlug: "labour-law",
  },
  {
    slug: "taxation-i",
    name: "Taxation Law I — Direct Taxes",
    shortName: "Tax Law I",
    description: "Principles of income tax and other direct taxes applicable in India.",
    icon: "Percent",
    tracks: ["4th Year Law"],
  },
  {
    slug: "taxation-ii",
    name: "Taxation Law II — Indirect Taxes",
    shortName: "Tax Law II",
    description: "GST and other indirect tax principles applicable in India.",
    icon: "Percent",
    tracks: ["4th Year Law"],
  },
  {
    slug: "ipr-i",
    name: "Intellectual Property Rights I (Copyright & Trademarks)",
    shortName: "IPR I",
    description: "Copyright and trademark protection, registration, and infringement.",
    icon: "Lightbulb",
    tracks: ["4th Year Law"],
    linkedSubjectSlug: "intellectual-property",
  },
  {
    slug: "ipr-ii",
    name: "Intellectual Property Rights II (Patents & Trade Secrets)",
    shortName: "IPR II",
    description: "Patent law, trade secrets, and other emerging forms of intellectual property.",
    icon: "Lightbulb",
    tracks: ["4th Year Law"],
    linkedSubjectSlug: "intellectual-property",
  },
  {
    slug: "pil-i",
    name: "Public International Law I",
    shortName: "PIL I",
    description: "Sources of international law, statehood, recognition, and state responsibility.",
    icon: "Globe2",
    tracks: ["4th Year Law"],
    linkedSubjectSlug: "international-law",
  },
  {
    slug: "pil-ii",
    name: "Public International Law II",
    shortName: "PIL II",
    description: "International organisations, use of force, and international dispute settlement.",
    icon: "Globe2",
    tracks: ["4th Year Law"],
    linkedSubjectSlug: "international-law",
  },
  {
    slug: "adr-i",
    name: "ADR & Arbitration I — Negotiation & Mediation",
    shortName: "ADR I",
    description: "Principles and skills of negotiation and mediation as alternatives to litigation.",
    icon: "Handshake",
    tracks: ["4th Year Law"],
  },
  {
    slug: "adr-ii",
    name: "ADR & Arbitration II — Arbitration Law & Practice",
    shortName: "ADR II",
    description: "Arbitration agreements, procedure, and enforcement under Indian arbitration law.",
    icon: "Handshake",
    tracks: ["4th Year Law"],
  },
  {
    slug: "banking-law-i",
    name: "Banking Law I",
    shortName: "Banking Law",
    description: "Regulation of banks, negotiable instruments, and banker-customer relationships.",
    icon: "Wallet",
    tracks: ["4th Year Law"],
  },
  {
    slug: "insurance-law-i",
    name: "Insurance Law I",
    shortName: "Insurance Law",
    description: "Principles of insurance contracts and the regulatory framework for insurers in India.",
    icon: "ShieldCheck",
    tracks: ["4th Year Law"],
  },
  {
    slug: "competition-law",
    name: "Competition Law",
    shortName: "Competition",
    description: "Anti-competitive agreements, abuse of dominance, and regulation of combinations.",
    icon: "Scale",
    tracks: ["4th Year Law"],
  },
  {
    slug: "cyber-law",
    name: "Cyber Law & IT Law",
    shortName: "Cyber Law",
    description: "Regulation of electronic records, digital signatures, and cyber offences under the IT Act.",
    icon: "Wifi",
    tracks: ["4th Year Law"],
    relatedActIds: ["it-act"],
  },
  {
    slug: "human-rights-i",
    name: "Human Rights Law I",
    shortName: "Human Rights I",
    description: "Constitutional and international human rights protections and their enforcement.",
    icon: "HeartHandshake",
    tracks: ["4th Year Law"],
  },
  {
    slug: "criminology-penology",
    name: "Criminology & Penology",
    shortName: "Criminology",
    description: "Theories of crime causation and the principles of punishment and prison reform.",
    icon: "Fingerprint",
    tracks: ["4th Year Law"],
  },
  {
    slug: "women-and-law",
    name: "Women & Law",
    shortName: "Women & Law",
    description: "Legal protections against gender-based discrimination and violence in India.",
    icon: "UserRound",
    tracks: ["4th Year Law"],
  },

  // ---------------------------------------------------------------------------
  // Year 5 — Advanced & Clinical
  // ---------------------------------------------------------------------------
  {
    slug: "human-rights-ii",
    name: "Human Rights Law II — International Mechanisms",
    shortName: "Human Rights II",
    description: "International human rights instruments and enforcement mechanisms such as UN treaty bodies.",
    icon: "HeartHandshake",
    tracks: ["5th Year Law"],
  },
  {
    slug: "banking-law-ii",
    name: "Banking Law II — Advanced",
    shortName: "Banking Law II",
    description: "Advanced banking regulation, recovery of debts, and banking sector reforms.",
    icon: "Wallet",
    tracks: ["5th Year Law"],
  },
  {
    slug: "insurance-law-ii",
    name: "Insurance Law II — Advanced",
    shortName: "Insurance Law II",
    description: "Advanced insurance regulation, claims, and dispute resolution in insurance.",
    icon: "ShieldCheck",
    tracks: ["5th Year Law"],
  },
  {
    slug: "drafting-pleading-ii",
    name: "Drafting, Pleading & Conveyancing II",
    shortName: "Drafting II",
    description: "Advanced drafting of commercial agreements, conveyance deeds, and specialised pleadings.",
    icon: "PenLine",
    tracks: ["5th Year Law"],
  },
  {
    slug: "moot-court-ii",
    name: "Moot Court & Trial Advocacy II",
    shortName: "Moot Court II",
    description: "Advanced advocacy, cross-examination technique, and appellate mooting.",
    icon: "Presentation",
    tracks: ["5th Year Law"],
  },
  {
    slug: "legal-aid-clinical",
    name: "Legal Aid & Clinical Legal Education",
    shortName: "Legal Aid",
    description: "Legal aid delivery, clinical legal education, and para-legal training.",
    icon: "LifeBuoy",
    tracks: ["5th Year Law"],
  },
  {
    slug: "professional-ethics",
    name: "Professional Ethics & Bar Council Rules",
    shortName: "Prof. Ethics",
    description: "Professional conduct rules for advocates and the standards enforced by Bar Councils.",
    icon: "BadgeCheck",
    tracks: ["5th Year Law"],
  },
  {
    slug: "dissertation-research",
    name: "Dissertation / Legal Research Methodology",
    shortName: "Dissertation",
    description: "Legal research methods, citation practice, and independent dissertation writing.",
    icon: "FlaskConical",
    tracks: ["5th Year Law"],
  },
  {
    slug: "constitutional-remedies",
    name: "Constitutional Remedies & Writ Jurisdiction",
    shortName: "Const. Remedies",
    description: "Writ jurisdiction of the Supreme Court and High Courts, and constitutional remedies for rights violations.",
    icon: "Landmark",
    tracks: ["5th Year Law"],
    relatedActIds: ["constitution"],
  },
  {
    slug: "international-trade-law",
    name: "International Trade Law",
    shortName: "Trade Law",
    description: "Regulation of cross-border trade, the WTO framework, and international commercial transactions.",
    icon: "Ship",
    tracks: ["5th Year Law"],
  },
  {
    slug: "ibc",
    name: "Insolvency & Bankruptcy Code (IBC)",
    shortName: "IBC",
    description: "Corporate insolvency resolution and liquidation under the Insolvency and Bankruptcy Code, 2016.",
    icon: "Banknote",
    tracks: ["5th Year Law"],
  },
  {
    slug: "media-press-law",
    name: "Media & Press Law",
    shortName: "Media Law",
    description: "Regulation of the press, broadcasting, and freedom of speech in the media.",
    icon: "Newspaper",
    tracks: ["5th Year Law"],
  },
  {
    slug: "consumer-protection-law",
    name: "Consumer Protection Law",
    shortName: "Consumer Law",
    description: "Consumer rights, unfair trade practices, and redress under consumer protection law.",
    icon: "ShoppingCart",
    tracks: ["5th Year Law"],
  },
  {
    slug: "election-law",
    name: "Election Law",
    shortName: "Election Law",
    description: "The constitutional and statutory framework governing elections in India.",
    icon: "Vote",
    tracks: ["5th Year Law"],
  },
  {
    slug: "corporate-governance",
    name: "Corporate Governance",
    shortName: "Corp. Governance",
    description: "Board accountability, disclosure norms, and governance standards for companies.",
    icon: "Building2",
    tracks: ["5th Year Law"],
  },
  {
    slug: "administrative-law-ii",
    name: "Administrative Law II",
    shortName: "Admin Law II",
    description: "Judicial review of administrative action, tribunals, and the accountability of the administrative state.",
    icon: "Scale",
    tracks: ["5th Year Law"],
    linkedSubjectSlug: "administrative-law",
  },

  // ---------------------------------------------------------------------------
  // CLAT
  // ---------------------------------------------------------------------------
  {
    slug: "clat-english",
    name: "English Language",
    shortName: "English",
    description: "Reading comprehension, vocabulary, and grammar in the CLAT format.",
    icon: "Languages",
    tracks: ["CLAT"],
  },
  {
    slug: "clat-current-affairs",
    name: "Current Affairs & General Knowledge",
    shortName: "Current Affairs",
    description: "Static and current general knowledge, with an emphasis on legally significant developments.",
    icon: "Newspaper",
    tracks: ["CLAT"],
  },
  {
    slug: "clat-legal-reasoning",
    name: "Legal Reasoning",
    shortName: "Legal Reasoning",
    description: "Applying legal principles to fact situations through CLAT's passage-based reasoning format.",
    icon: "Scale",
    tracks: ["CLAT"],
  },
  {
    slug: "clat-logical-reasoning",
    name: "Logical Reasoning",
    shortName: "Logical Reasoning",
    description: "Critical reasoning, argument analysis, and logical inference for CLAT.",
    icon: "Brain",
    tracks: ["CLAT"],
  },
  {
    slug: "clat-quant",
    name: "Quantitative Techniques",
    shortName: "Quant",
    description: "Elementary mathematics and data interpretation as tested in CLAT.",
    icon: "Calculator",
    tracks: ["CLAT"],
  },

  // ---------------------------------------------------------------------------
  // Judiciary — core areas not already covered by a reused rich subject above.
  // Constitutional Law, Criminal Law, Contract Law, Torts, Family Law, Property
  // Law, and Administrative Law are shared with the rich subjects above (their
  // `tracks` include "Judiciary"), since state judiciary syllabi vary but
  // consistently draw on the same doctrinal subjects law schools already teach.
  // ---------------------------------------------------------------------------
  {
    slug: "judiciary-criminal-procedure",
    name: "Criminal Procedure",
    shortName: "Crim. Procedure",
    description: "Procedural criminal law tested across judiciary exams — arrest, investigation, trial, and appeal — drawing on the BNSS/CrPC and state amendments.",
    icon: "ClipboardList",
    tracks: ["Judiciary"],
    linkedSubjectSlug: "bnss",
  },
  {
    slug: "judiciary-civil-procedure",
    name: "Civil Procedure",
    shortName: "Civil Procedure",
    description: "Procedural civil law tested across judiciary exams under the CPC, 1908, including state-specific amendments.",
    icon: "FileStack",
    tracks: ["Judiciary"],
    linkedSubjectSlug: "cpc",
  },
  {
    slug: "judiciary-evidence",
    name: "Law of Evidence",
    shortName: "Evidence",
    description: "Rules of evidence tested across judiciary exams under the BSA and the historical Evidence Act.",
    icon: "FileSearch",
    tracks: ["Judiciary"],
    linkedSubjectSlug: "evidence-bsa",
  },
  {
    slug: "local-state-laws",
    name: "Local/State Laws",
    shortName: "State Laws",
    description: "State-specific enactments and local amendments relevant to a particular state's judiciary exam — syllabi vary significantly by state.",
    icon: "MapPin",
    tracks: ["Judiciary"],
  },
  {
    slug: "legal-current-affairs",
    name: "Legal Current Affairs",
    shortName: "Legal Current Affairs",
    description: "Recent judgments, ordinances, and legislative developments relevant to judiciary exams.",
    icon: "Newspaper",
    tracks: ["Judiciary"],
  },
  {
    slug: "judgment-writing",
    name: "Judgment Writing",
    shortName: "Judgment Writing",
    description: "The structure and technique of writing a reasoned judicial judgment.",
    icon: "PenLine",
    tracks: ["Judiciary"],
  },
  {
    slug: "answer-writing",
    name: "Answer Writing",
    shortName: "Answer Writing",
    description: "Structuring precise, legally sound answers for judiciary mains examinations.",
    icon: "ListChecks",
    tracks: ["Judiciary"],
  },
  {
    slug: "bare-act-practice",
    name: "Bare Act Practice",
    shortName: "Bare Act Practice",
    description: "Direct practice reading and applying Bare Act provisions, a core judiciary exam skill.",
    icon: "BookOpenCheck",
    tracks: ["Judiciary"],
  },
  {
    slug: "judiciary-pyqs",
    name: "Previous Year Questions",
    shortName: "PYQs",
    description: "Practice with previous years' judiciary prelims and mains questions.",
    icon: "History",
    tracks: ["Judiciary"],
  },
];

export function getSubjectBySlug(slug: string) {
  return subjects.find((s) => s.slug === slug);
}

/** Subjects belonging to a given onboarding preparation track (year, CLAT, or Judiciary). */
export function getSubjectsForTrack(lawLevel: string | null | undefined) {
  if (!lawLevel) return [];
  return subjects.filter((s) => (s.tracks as string[]).includes(lawLevel));
}

/**
 * Resolves the slug whose quiz/flashcard/case content should be used for a
 * curriculum subject — its own slug for rich subjects, or the rich subject it
 * links to for a curriculum-only entry (e.g. "Constitutional Law I" -> "constitutional-law").
 */
export function getPracticeSlug(subject: Subject) {
  return subject.linkedSubjectSlug ?? subject.slug;
}
