import type { Metadata } from "next";
import { Navbar } from "@/components/navigation/navbar";
import { Footer } from "@/components/navigation/footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms for using StudyRex.",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="font-heading text-lg font-semibold text-foreground">{title}</h2>
      <div className="mt-2 space-y-3 text-sm leading-relaxed text-muted-foreground">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1">
        <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 lg:px-8">
          <h1 className="font-heading text-3xl font-semibold tracking-tight text-foreground">Terms of Service</h1>

          <Section title="Educational use only">
            <p>
              StudyRex, including the AI Tutor, is an educational study aid for Indian law. It is not a
              lawyer, does not provide legal advice, and nothing it generates should be relied on for an
              actual legal matter. Always verify specific provisions against the current Bare Act or a
              qualified professional.
            </p>
          </Section>

          <Section title="AI-generated content">
            <p>
              Answers are generated by Anthropic&apos;s Claude model based on your question and context. While
              StudyRex is built to cite specific provisions and flag when something needs verification, AI
              output can still be wrong. Treat it as a study aid, not a source of record.
            </p>
          </Section>

          <Section title="Your account">
            <p>You&apos;re responsible for keeping your password secure and for the accuracy of the information you provide. Don&apos;t share your account with others.</p>
          </Section>

          <Section title="Acceptable use">
            <p>Don&apos;t use StudyRex to generate or distribute unlawful content, attempt to extract or abuse the underlying AI system, or interfere with other users&apos; access to the service.</p>
          </Section>

          <Section title="Changes">
            <p>These terms may be updated as StudyRex evolves. Continuing to use the product after a change means you accept the update.</p>
          </Section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
